name: Find difference
on:
  workflow_dispatch:
    inputs:
      version_1:
        description: 'Type first version need to compare here:'
        required: true
        type: string
      version_2:
        description: 'Type second version need to compare here:'
        required: true
        type: string
  workflow_call:
    inputs:
      version_1:
        required: true
        type: string
      version_2:
        required: true
        type: string
jobs:
  find_difference:
    name: Find difference
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Find difference
        run: bash src/find_release.sh
        env:
          repository: ${{ github.repository }}
          first_version: ${{ github.event.inputs.version_1 }}
          second_version: ${{ github.event.inputs.version_2 }}
      - name: Generate release info
        shell: bash
        run: |
          echo "
          **Change log** :point_down:
          "> ${{ github.workspace }}-CHANGELOG.txt
      - name: Release
        uses: ncipollo/release-action@v1.14.0
        with:
          artifacts: |
            ./release/*.apk
          name: Revanced & Revanced Extended
          tag: all
          bodyFile: ${{ github.workspace }}-CHANGELOG.txt
